openapi: 3.1.0
info:
  title: Exogenesis Ensemble Part 3 (Redemption)
  description: Exogenesis Ensemble Part 3 (Redemption) API
  version: 1.0.0
paths:
  /bucket/videos:
    get:
      tags:
        - Bucket
      summary: existing video's year
      description: returns years of the bucket prefix hosted in the S3
      operationId: getExistingYearsInBucket
      responses:
        '200':
          description: videos
          content:
            'application/json':
              schema:
                type: object
                description: years
                properties:
                  years:
                    type: array
                    items:
                      type: string
    post:
      tags:
        - Bucket
      summary: upload a video
      description: This API returns the pre-signed URL for uploading the video. You must upload the video via that URL.
      requestBody:
        content:
          "application/json":
            schema:
              type: object
              properties:
                dateTime:
                  type: string
                  description: The dateTime is the ISO date time format.
              required:
                - dateTime
            example:
              dateTime: "1984-04-04 00:00:00.000"
      responses:
        200:
          description: the pre-signed URL
          content:
            'application/json':
              schema:
                type: object
                description: pre-signed URL
                properties:
                  url:
                    type: string
              example:
                url: "https://pre-signed-url/path/to/vide.mov"

  /bucket/videos/years/{year}/months:
    get:
      tags:
        - Bucket
      summary: existing video's month
      description: returns months of the bucket prefix hosted in the S3 by narrowed down by the year
      operationId: getExistingMonthsInBucket
      parameters:
        - name: year
          in: path
          required: true
          description: Year
          schema:
            type: string
      responses:
        '200':
          description: videos
          content:
            'application/json':
              schema:
                type: object
                description: months
                properties:
                  months:
                    type: array
                    items:
                      type: string
  /bucket/videos/years/{year}/months/{month}/days:
    get:
      tags:
        - Bucket
      summary: existing video's days
      description: returns months of the bucket prefix hosted in the S3 by narrowed down by the year
      operationId: getExistingDaysInBucket
      parameters:
        - name: year
          in: path
          required: true
          description: Year
          schema:
            type: string
        - name: month
          in: path
          required: true
          description: Month
          schema:
            type: string
      responses:
        '200':
          description: videos
          content:
            'application/json':
              schema:
                type: object
                description: days
                properties:
                  days:
                    type: array
                    items:
                      type: string
  /bucket/videos/years/{year}/months/{month}/days/{day}/objects:
    get:
      tags:
        - Bucket
      summary: existing video's days
      description: returns months of the bucket prefix hosted in the S3 by narrowed down by the year
      operationId: getExistingObjectsInBucket
      parameters:
        - name: year
          in: path
          required: true
          description: Year
          schema:
            type: string
        - name: month
          in: path
          required: true
          description: Month
          schema:
            type: string
        - name: day
          in: path
          required: true
          description: Day
          schema:
            type: string
      responses:
        '200':
          description: videos
          content:
            'application/json':
              schema:
                type: array
                items:
                  objects: string

components:
  schemas:
    Video:
      type: object
      properties:
        year:
          type: integer
        month:
          type: integer
        day:
          type: integer
        name:
          type: string
