name: Test Build

on:
  pull_request:
    branches:
      - dev

jobs:
  test-build-project-doc:
    timeout-minutes: 3
    name: build a project
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs/project
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install package
        run: bun install
      - name: Check format
        run: bun run build

  test-build-top-page-doc:
    timeout-minutes: 2
    name: build a top page
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs/top-page
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install package
        run: bun install
      - name: Check format
        run: bun run build

  test-build-web-api-doc:
    timeout-minutes: 3
    name: build a web API document
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lambdas/web-api-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: mkdir
        run: sudo mkdir /build && sudo chmod -R 777 /build
      - name: Setup Cargo
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: build
        run: cargo doc --all --no-deps --document-private-items

  test-build-s3-hook-doc:
    timeout-minutes: 3
    name: build a s3 hook document
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lambdas/s3-hook-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: mkdir
        run: sudo mkdir /build && sudo chmod -R 777 /build
      - name: Setup Cargo
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: build
        run: cargo doc --all --no-deps --document-private-items

  test-native-back-end-api-doc:
    timeout-minutes: 5
    name: build the native back end app api doc
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/src-tauri
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Setup Cargo
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: cargo doc --all --no-deps --document-private-items

  test-native-front-doc:
    timeout-minutes: 1
    name: build the native front-end app api doc
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install package
        run: bun install
      - name: Run TypeDoc
        run: bun run typedoc

  action-timeline:
    needs:
      - test-build-project-doc
      - test-build-top-page-doc
      - test-native-back-end-api-doc
      - test-native-front-doc
      - test-build-s3-hook-doc
      - test-build-web-api-doc
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v2
