name: Code Quality

on:
  pull_request:
    branches:
      - dev

jobs:
  check-project-doc:
    timeout-minutes: 3
    name: test project document quality
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs/project
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install package
        run: bun install
      - name: Check format
        run: bun run format:check
      - name: Check type
        run: bun run typecheck

  check-top-page-doc:
    timeout-minutes: 3
    name: test top page quality
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs/top-page
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install package
        run: bun install
      - name: Check format
        run: bun run format:check

  check-native-back-end:
    timeout-minutes: 3
    name: check the native back end app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/src-tauri
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Setup Cargo
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: cargo check

  check-native-front-end:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install package
        run: bun install
      - name: Run TSC
        run: bun tsc
      - name: Check format
        run: bun run format:check

  action-timeline:
    needs: [check-project-doc, check-top-page-doc, check-native-back-end, check-native-front-end]
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v2